### ISSUE TITLE
当app挂载的view是canvas时，app无法正常加载出点阵效果

### ISSUE THREAD

**Issue by Max0897** [tuntun0609/leafer-x-dot-matrix#1]
当app挂载的view是canvas时，app无法正常加载出点阵效果

**Comment by tuntun0609** [comment]
建议挂载 div 元素，插件的本质是新建一个leafer 实例，也就是一个新的 canvas 在 tree 层 canvas 的下层展示，如果直接挂载在一个 canvas 上的话，可能导致点阵渲染和其他元素冲突
